{
    'name': "Gestión de Clínica",
    'version': '1.0',
    'summary': 'Modulo para gestionar pacientes',
    'category': 'Healthcare',
    'depends': ['base'],
    'data': [
        'security/groups.xml',
        'security/ir.model.access.csv',
        'data/sequence.xml',
        'data/cron.xml',
        'views/medico_view.xml',
        'views/medico_horario_view.xml',
        'views/slot_view.xml',
        'views/ausencia_view.xml',
        'views/paciente_view.xml',
        'views/cita_view.xml',
        'views/menu.xml',
    ],
    'demo': [
        'demo/paciente_demo.xml',
    ],
    'installable': True,
    'application': True,
}